apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-certs
  namespace: elk
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  namespace: elk
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm