daemonset:
  filebeatConfig:
    filebeat.yml: |
      ssl.enabled: false
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      output.logstash:
        hosts: ["elk-logstash-logstash:5044"]
        ssl.enabled: false
        protocol: "http"
        ssl.verification_mode: none


      filebeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  equals:
                    kubernetes.container.name: "nginx-ingress-controller"
                config:
                - module: nginx
                  access:
                    enabled: true
                    input:
                      type: container
                      paths:
                      - /var/lib/docker/containers/${data.kubernetes.container.id}/*.log
      output.elasticsearch:
        hosts: 'elasticsearch-service:9200'