apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: aipaints
  name: aipaints-pvc
  namespace: wordpress-aipaints
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aipaints-app
  name: aipaints-app
  namespace: wordpress-aipaints
  annotations:
    backup.velero.io/backup-volumes: aipaints-pv
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: aipaints-app
  template:
    metadata:
      labels:
        app: aipaints-app
    spec:
      containers:
        # redis is at redis-service.wordpressdb.svc.cluster.local
        - env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-service.wordpressdb.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: aipaints
            - name: WORDPRESS_DB_NAME
              value: wordpress_aipaints
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aipaintswppw 
                  key: MARIADB_PASSWORD
          image: wordpress:latest
          imagePullPolicy: Always
          name: aipaints-app
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: 128m
            limits:
              memory: "1Gi"
              cpu: 1000m
          volumeMounts:
            - mountPath: /var/www/html
              name: aipaints-pv
      restartPolicy: Always
      volumes:
        - name: aipaints-pv
          persistentVolumeClaim:
            claimName: aipaints-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aipaints
  name: aipaints-service
  namespace: wordpress-aipaints
spec:
  ports:
    - name: "aipaints-service"
      port: 80
      targetPort: 80
  selector:
    app: aipaints-app