apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dfcontabo
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@datafortress.cloud
    privateKeySecretRef:
      name: letsencrypt-dfcontabo
    solvers:
      - http01:
          ingress:
            class: nginx